name: dotnet-ci

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: |
          6.x
          8.x
    - name: dotnet info
      run: dotnet --info
    - name: dotnet test GetStarted 
      run: dotnet test P1_GetStarted/GetStarted.sln
    - name: dotnet test AutoFac 
      run: dotnet test P2_AutoFac/AutoFacIntegration.sln
    - name: dotnet test AspectCore 
      run: dotnet test P3_AspectCore/AspectCoreIntegration.sln
    - name: dotnet test TestServer 
      run: dotnet test P4_TestServer/TestServerIntegration.sln
    - name: dotnet test More 
      run: dotnet test P5_More/MoreFeatures.sln
    - name: dotnet test MinimalAPI
      run: dotnet test P6_MinimalAPI/MinimalApiSample.sln
